### ISSUE TITLE
Sentry の guard が一瞬で drop されてる

### ISSUE THREAD

**Issue by kory33** [GiganticMinecraft/seichi-portal-backend#164]
https://github.com/GiganticMinecraft/seichi-portal-backend/blob/719dcdc68d9aa37b6d0defc4391ea8c5cf7d097a/server/entrypoint/src/main.rs#L27-L37

**Comment by kory33** [comment]
こうするべき
https://github.com/GiganticMinecraft/seichi-timed-stats-conifers/commit/3311d55bb65359e27eb846d7c86b898600453ec0

**Comment by LoliGothick** [comment]
#173
